---
- name: Remove legacy key
  ansible.builtin.apt_key:
    id: F209D8762A60CD49E680633B4FF8368B6EA0722A
    state: absent
  tags:
    - fluentbit

- name: Remove legacy repo
  ansible.builtin.apt_repository:
    repo: "deb https://packages.fluentbit.io/{{ fluentbit_repo_distribution }}/{{ fluentbit_repo_release }} {{ fluentbit_repo_release }} main"
    filename: fluentbit
    update_cache: False
    state: absent
  tags:
    - fluentbit

- name: Download repo key
  ansible.builtin.shell:
    cmd: "curl -sSL 'https://packages.fluentbit.io/fluentbit.key' | gpg --dearmor --output {{ fluentbit_keyring }}"
    creates: "{{ fluentbit_keyring }}"
  tags:
    - fluentbit

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ fluentbit_keyring }}] https://packages.fluentbit.io/{{ fluentbit_repo_distribution }}/{{ fluentbit_repo_release }} {{ fluentbit_repo_release }} main"
    filename: fluentbit
    update_cache: True
    state: present
  tags:
    - fluentbit

- name: Install required packages
  loop:
    - td-agent-bit
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - fluentbit

- name: Create required directories
  loop:
    - /var/lib/td-agent-bit
    - /etc/td-agent-bit/config.d
    - /etc/td-agent-bit/input.d
    - /etc/td-agent-bit/filter.d
    - /etc/td-agent-bit/output.d
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - fluentbit

- name: Drop plugins config
  notify:
    - Restart fluentbit
  ansible.builtin.file:
    path: /etc/td-agent-bit/plugins.conf
    state: absent
  tags:
    - fluentbit

- name: Write service config
  notify:
    - Restart fluentbit
  ansible.builtin.template:
    src: config.j2
    dest: /etc/td-agent-bit/td-agent-bit.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - fluentbit

- name: Write parsers config
  notify:
    - Restart fluentbit
  ansible.builtin.template:
    src: parsers.j2
    dest: /etc/td-agent-bit/parsers.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - fluentbit

- name: Write dummy configs
  notify:
    - Restart fluentbit
  loop:
    - config
    - input
    - filter
    - output
  ansible.builtin.copy:
    content: "# just created to keep imports working"
    dest: "/etc/td-agent-bit/{{ item }}.d/_dummy.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - fluentbit

- name: Write combined configs
  notify:
    - Restart fluentbit
  loop: "{{ fluentbit_default_configs + fluentbit_group_configs + fluentbit_host_configs + fluentbit_extra_configs }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'present'
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: /etc/td-agent-bit/config.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - fluentbit

- name: Remove combined configs
  notify:
    - Restart fluentbit
  loop: "{{ fluentbit_default_configs + fluentbit_group_configs + fluentbit_host_configs + fluentbit_extra_configs }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'absent'
  ansible.builtin.file:
    path: /etc/td-agent-bit/config.d/{{ item.name }}.conf
    state: absent
  tags:
    - fluentbit

- name: Write input configs
  notify:
    - Restart fluentbit
  loop: "{{ fluentbit_default_inputs + fluentbit_group_inputs + fluentbit_host_inputs + fluentbit_extra_inputs }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'present'
  ansible.builtin.template:
    src: input.j2
    dest: /etc/td-agent-bit/input.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - fluentbit

- name: Remove input configs
  notify:
    - Restart fluentbit
  loop: "{{ fluentbit_default_inputs + fluentbit_group_inputs + fluentbit_host_inputs + fluentbit_extra_inputs }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'absent'
  ansible.builtin.file:
    path: /etc/td-agent-bit/input.d/{{ item.name }}.conf
    state: absent
  tags:
    - fluentbit

- name: Write filter configs
  notify:
    - Restart fluentbit
  loop: "{{ fluentbit_default_filters + fluentbit_group_filters + fluentbit_host_filters + fluentbit_extra_filters }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'present'
  ansible.builtin.template:
    src: filter.j2
    dest: /etc/td-agent-bit/filter.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - fluentbit

- name: Remove filter configs
  notify:
    - Restart fluentbit
  loop: "{{ fluentbit_default_filters + fluentbit_group_filters + fluentbit_host_filters + fluentbit_extra_filters }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'absent'
  ansible.builtin.file:
    path: /etc/td-agent-bit/filter.d/{{ item.name }}.conf
    state: absent
  tags:
    - fluentbit

- name: Write output configs
  notify:
    - Restart fluentbit
  loop: "{{ fluentbit_default_outputs + fluentbit_group_outputs + fluentbit_host_outputs + fluentbit_extra_outputs }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'present'
  ansible.builtin.template:
    src: output.j2
    dest: /etc/td-agent-bit/output.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - fluentbit

- name: Remove output configs
  notify:
    - Restart fluentbit
  loop: "{{ fluentbit_default_outputs + fluentbit_group_outputs + fluentbit_host_outputs + fluentbit_extra_outputs }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'absent'
  ansible.builtin.file:
    path: /etc/td-agent-bit/output.d/{{ item.name }}.conf
    state: absent
  tags:
    - fluentbit

- name: Start fluentbit service
  ansible.builtin.systemd:
    name: td-agent-bit
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - fluentbit

...
